# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{freshtrack}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yossef Mendelssohn"]
  s.date = %q{2011-03-29}
  s.default_executable = %q{freshtrack}
  s.email = %q{ymendel@pobox.com}
  s.executables = ["freshtrack"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
    "License.txt",
    "Manifest.txt",
    "README.txt",
    "Rakefile",
    "VERSION",
    "bin/freshtrack",
    "config/hoe.rb",
    "config/requirements.rb",
    "lib/freshbooks/extensions.rb",
    "lib/freshbooks/extensions/base_object.rb",
    "lib/freshbooks/extensions/invoice.rb",
    "lib/freshbooks/extensions/project.rb",
    "lib/freshbooks/extensions/task.rb",
    "lib/freshbooks/extensions/time_entry.rb",
    "lib/freshtrack.rb",
    "lib/freshtrack/core_ext.rb",
    "lib/freshtrack/core_ext/array.rb",
    "lib/freshtrack/core_ext/numeric.rb",
    "lib/freshtrack/core_ext/time.rb",
    "lib/freshtrack/time_collectors/one_inch_punch.rb",
    "lib/freshtrack/time_collectors/punch.rb",
    "lib/freshtrack/time_collectors/punchy_template.rb",
    "lib/freshtrack/version.rb",
    "log/debug.log",
    "script/destroy",
    "script/generate",
    "setup.rb",
    "spec/.bacon",
    "spec/core_ext/array_spec.rb",
    "spec/core_ext/numeric_spec.rb",
    "spec/core_ext/time_spec.rb",
    "spec/freshbooks/base_object_spec.rb",
    "spec/freshbooks/invoice_spec.rb",
    "spec/freshbooks/payment_spec.rb",
    "spec/freshbooks/project_spec.rb",
    "spec/freshbooks/task_spec.rb",
    "spec/freshbooks/time_entry_spec.rb",
    "spec/freshtrack_command_spec.rb",
    "spec/freshtrack_spec.rb",
    "spec/spec_helper.rb",
    "spec/time_collectors/one_inch_punch_spec.rb",
    "spec/time_collectors/punch_spec.rb",
    "tasks/deployment.rake",
    "tasks/environment.rake",
    "tasks/rspec.rake",
    "tasks/website.rake"
  ]
  s.homepage = %q{http://github.com/flogic/freshtrack}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Track your time on FreshBooks}
  s.test_files = [
    "spec/core_ext/array_spec.rb",
    "spec/core_ext/numeric_spec.rb",
    "spec/core_ext/time_spec.rb",
    "spec/freshbooks/base_object_spec.rb",
    "spec/freshbooks/invoice_spec.rb",
    "spec/freshbooks/payment_spec.rb",
    "spec/freshbooks/project_spec.rb",
    "spec/freshbooks/task_spec.rb",
    "spec/freshbooks/time_entry_spec.rb",
    "spec/freshtrack_command_spec.rb",
    "spec/freshtrack_spec.rb",
    "spec/spec_helper.rb",
    "spec/time_collectors/one_inch_punch_spec.rb",
    "spec/time_collectors/punch_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<freshbooks>, ["= 2.1"])
      s.add_development_dependency(%q<bacon>, [">= 1.1.0"])
      s.add_development_dependency(%q<facon>, [">= 0.4.1"])
    else
      s.add_dependency(%q<freshbooks>, ["= 2.1"])
      s.add_dependency(%q<bacon>, [">= 1.1.0"])
      s.add_dependency(%q<facon>, [">= 0.4.1"])
    end
  else
    s.add_dependency(%q<freshbooks>, ["= 2.1"])
    s.add_dependency(%q<bacon>, [">= 1.1.0"])
    s.add_dependency(%q<facon>, [">= 0.4.1"])
  end
end

